FROM python:3.7-alpine

# Setting the working directory
WORKDIR /usr/app/src

# Copying the python file to present working directory
COPY Mount_Directory_to_container.py ./

CMD [ "python3", "Mount_Directory_to_container.py"]